server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:localhost.p12
    key-store-password: ${KEYSTORE_PASSWORD}
    key-store-type: PKCS12
  http2:
    enabled: true
  compression:
    enabled: true
    min-response-size: 1
    mime-types: text/html,text/xml,text/plain,application/json

logging:
  level:
    root: INFO

openapi:
  server-url: https://myserver.com
