server:
  port: 8080
  ssl:
    enabled: false
  http2:
    enabled: false
  compression:
    enabled: true
    min-response-size: 1
    mime-types: text/html,text/xml,text/plain,application/json

logging:
  level:
    root: DEBUG

openapi:
  server-url: http://localhost:8080
